### ISSUE TITLE
List of places where examining an item does not activate Examination Log:

### ISSUE THREAD

**Issue by Strelark** [CarlOmega/examine-log#1]
- Equipped items (armor / weapons)
- Runes stored in rune pouch

**Comment by source-chunk** [comment]
- Items in your bank

**Comment by jbcaud** [comment]
![image](https://github.com/user-attachments/assets/8a011bfd-0a45-4cbe-8246-b631a725a006)
The developer left this comment which seems relevant to this thread. Right now events from other sources besides the environment (NPC, object, ground items) or inventory are intentionally ignored. I'm not sure exactly what they meant by abusing this with other widgets but I'm sure they can explain further.

**Comment by CarlOmega** [comment]
It was intentional but can see the value of allowing banked items and equipment. 

The main challenge for banked items is you wont receive popups since the bank is taking that interface slot. I could rework it to allow a chat message instead. But originally wanted to avoid people just spamming their bank straight away. 

Additionally with equipment there isnt any major technical limitation but I put in a blanket check that has to be examined from your inventory. Otherwise during my play testing I could go to my poh and treasure box to examine all mega rare clue rewards. 

Again these aren't really issues but if people want this as a feature I will look into adding it in.
