### ISSUE TITLE
[SUGGESTION] Option to hide examine options that are already in log

### ISSUE THREAD

**Issue by wigglyworm91** [CarlOmega/examine-log#9]
So instead of showing `Examine* Bank booth` and `Examine STASH (master)` the second one would just have the option hidden.

**Comment by CarlOmega** [comment]
Have included this option in https://github.com/runelite/plugin-hub/pull/7057

Note due to limitation/time atm I hide when any examine for that particular object/npc/item is found. I will look in the future to only hide if you have the examine text. An example of this is "Tree" since it has multiple examine texts.

**Comment by CarlOmega** [comment]
PR should be merged now.
